language: node_js
os:
- osx
- linux
osx_image: xcode7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz; tar xzf android-sdk_r24.4.1-linux.tgz; export ANDROID_HOME=$PWD/android-sdk-linux; export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools${ANDROID_HOME}/build-tools/23.0.2; echo y | android update sdk --all --filter platform-tools,tools,build-tools-23.0.2,android-23,extra-android-support,extra-google-google_play_services,extra-google-m2repository,addon-google_apis-google-23,extra-android-m2repository --no-ui --force; sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1; fi
- "npm install -g cordova"
- "npm install -g plugman"
- "cordova create Test"
- "cd Test"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cordova platform add android --save; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cordova platform add ios --save; fi
script:
- "cordova plugin add ../"
- "cordova clean"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ORG_GRADLE_PROJECT_cdvMinSdkVersion=18; printf "ext.postBuildExtras = {\n\tandroid {\n\t\tcompileOptions {\n\t\t\tsourceCompatibility JavaVersion.VERSION_1_7\n\t\t\ttargetCompatibility JavaVersion.VERSION_1_7\n\t\t}\n\t}\n}\n" > Test/platforms/android/build-extras.gradle; cordova build android --stacktrace --debug; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then cordova build ios; fi
notifications:
  email:
    recipients:
      secure: "l5FhA6wRIONgku6V12/WhDGUX4I/LuirjLLp/dbrmfmPLwtDVNDg8hnIMjHZ/e33goU0ffwYik/Bv0qzSNSMglBIesOUoDPpke6bUALC4tUOC0KpDaTRGQiGPt7McKHqvwPvNHk4DnYKeq1PhoK59qa6rPki59wa4lvjXjUpTnThMtxNHa+cIVhLwdf3wctLAGBI/aeHTFNWM0reT7saj3ydjZYczITaU7fAywkmoawmZyqng8cbAIk76gx80YgtGoYtxaoXqPtGFvZXyWaLgTUMbXJwX4E/aEf8KstpZx0M2TO0kpTQtrjEYcTYfqNp1J5T8yyfh1sUEBCrblYbwDF2uM7ae7Vkg0hFziPXtLYctDOjx9crMaQbQmh6OganGjnfN9odMKk79RwC1+lQ4yxIHSiDfcHenoAbh9dpGhy9wm2Wh6UFNAktkKFOWym2kJ9JDWpnW0UdoX2Mttl0IVxiF0wUWsRmYcs13L4GuxOWlWBz1YkGEWx7QPyBA0ibasu64J2VJFJZSv+v6QSkJQ3zj/TDn53lJ/awx9ckjQlu6NM715pfz8cZk1ZcEnxhIU/mV/vNLtNtD1efs6nrjcvX+7bc/8grYFwWbKqt3h8ecYdr3H2elAJav+OuhhOUpII7dpeFgoY4axauLh7irT2QLv5rK+h8yzZhGv0w7ZY="
